# Generated by Django 3.2.7 on 2021-09-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_picture',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
