# Generated by Django 3.2.7 on 2021-09-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210925_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_icon',
            field=models.CharField(default='', max_length=30),
        ),
    ]
