# Generated by Django 3.2.7 on 2021-09-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_services_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_icon',
            field=models.CharField(default='', max_length=60),
        ),
    ]
